AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: App to check europe-exchange-rate for different currencies
  SAM Template for europe-exchange-rate

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.9
    Timeout: 180
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Parameters:
  ExchangeRatesTableArn:
    Description: Please enter the arn of the DynamoDB Exchange Rates table
    Type: String
    Default: arn:aws:dynamodb:us-east-1:801446212911:table/ExchangeRates

  GatewayLambdaInvokePolicyArn:
    Description: Please enter the arn of the lambda invoke policy
    Type: String
    Default: arn:aws:lambda:us-east-1:801446212911:function:*


Resources:
  RequirementsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: req
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9


  # APIGatewayRole enables API gateway access to DynamoDB
  APIGatewayRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: APIGatewayDynamoDBPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:PutItem'
                  - 'dynamodb:Query'
                # Including * in the resource Arn allows access to the DynamoDB table and indexes
                Resource: !Sub
                  - '${varTableArn}*'
                  - varTableArn: !Ref ExchangeRatesTableArn

  # APIGatewayRole enables API gateway trigger Lambda functions
  APIGatewayLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
      Policies:
        - PolicyName: APIGatewayLambdaInvokePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !Ref GatewayLambdaInvokePolicyArn

  ExchangeRateApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Exchange Rate Api
      StageName: Prod
      OpenApiVersion: '3.0.1'
      MethodSettings:
        - HttpMethod: '*'        # Mandatory
          ResourcePath: '/*'        # Mandatory
          LoggingLevel: ERROR
          DataTraceEnabled: true
          MetricsEnabled: true
      EndpointConfiguration:
        Type: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: swagger.yaml

  SaveExchangeRatesSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
#      CodeUri: api/
      Handler: api.lmd_exchange.save_current_exchange_rates
      Description: Scheduled Task function to get Every day exchange rates and save in DynamoDB
      Timeout: 900
      Layers:
        - !Ref RequirementsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        ExchangeStream:
          Type: Schedule
          Properties:
            Schedule: cron(0/720 * * * ? *)
            Name: SaveExchangeRatesSync
            Description: Start exchange sync after every 12 hours to check whether new data came in
            Enabled: True

  CurrentExchangeRates:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
#      CodeUri: api/
      Handler: api.lmd_exchange.get_current_exchange_rates
      Description: API gateway function to get and check current exchange rates
      MemorySize: 1024
      Layers:
        - !Ref RequirementsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonAPIGatewayAdministrator

  CompareExchangeRates:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
#      CodeUri: api/
      Handler: api.lmd_exchange.compare_exchange_rates
      Description: API gateway function to get and compare exchange rates for today and previous day
      MemorySize: 1024
      Layers:
        - !Ref RequirementsLayer
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonAPIGatewayAdministrator

  # Create the dynamoDB table first time
  ExchangeRates:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: ExchangeRates
      AttributeDefinitions:
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: date
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0


#  ApplicationInsightsMonitoring:
#    Type: AWS::ApplicationInsights::Application
#    Properties:
#      ResourceGroupName:
#        Fn::Join:
#        - ''
#        - - ApplicationInsights-SAM-
#          - Ref: AWS::StackName
#      AutoConfigurationEnabled: 'true'
#    DependsOn: ApplicationResourceGroup


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExchangeRateApi:
    Description: "Exchange Rate Api Endpoint Url"
    Value: !Sub
